### ISSUE TITLE
cpu_uptime_version_drives.sh lock machine

### ISSUE THREAD

**Issue by fk319** [J-C-B/freenas_splunk#22]
when I run cpu_uptime_version_drives.sh manually all seems well until I access the /var/log drive.  This drive is mapped to:
/var/db/system/syslog-5ece5c906a8f4df886779fae5cade8a5
after I cd to the directory and do an 'ls', I am not longer able to use the terminal.  I cannot log in.  If I have another session open I am fine, until I access the /var/log directory.

**Comment by fk319** [comment]
If I 'exit' before "#Get Drive info" I am fine.

**Comment by J-C-B** [comment]
Hi, what happens if you run `sysctl -n kern.disks` directly? what version of FreeNAS are you running? why are the events related? as in why are you running the script then going to that directory? the scripts are meant to be on a cron schedule, with syslog being forwarded to Splunk. Cheers

**Comment by fk319** [comment]
here are your answers: 

[root@freenas] ~/TA-SH_files_for_freenas# sysctl -n kern.disks
ada0 da7 da6 da5 da4 da3 da2 da1 da0
[root@freenas] ~/TA-SH_files_for_freenas# cat /etc/version
FreeNAS-9.3-STABLE-201602031011
[root@freenas] ~/TA-SH_files_for_freenas# 

When I first ran the scripts it locked up my machine.  I was looking at
/var/log for details and that is when I noticed the issue. 

I seem to be able to run:
    smartctl -a /dev/$i
on each of the devices with out issue. 

Frank 

On 02/18/2016 1:56 am, John wrote: 

> Hi, what happens if you run sysctl -n kern.disks directly? what version of FreeNAS are you running? why are the events related? as in why are you running the script then going to that directory? the scripts are meant to be on a cron schedule, with syslog being forwarded to Splunk. Cheers 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1]
https://github.com/J-C-B/freenas_splunk/issues/22#issuecomment-185569446

**Comment by J-C-B** [comment]
Unable to replicate on several machines (Physical and virtual)

**Comment by fk319** [comment]
Thank you for looking in to it.
