### ISSUE TITLE
CPU/HDD temps show zero when the cron interval is > 1min

### ISSUE THREAD

**Issue by ljdelight** [J-C-B/freenas_splunk#29]
The freenas-splunk app dashboard show 0C for the HDD and CPU temperatures when the splunk job exec interval doesn't match the cron interval. Look at [this screenshot](http://imgur.com/a/hW1kq) to see what I mean.

I'm new to splunk and don't know if this is the correct fix, but using timechart's `CONT=false` argument removes the zero entries and seems to fix the graph.
```
source="freenas" index="freenas" sourcetype="syslog" cpuid="*" host=* | timechart CONT=false max(temperature)
```

**Comment by J-C-B** [comment]
Hi, thanks for the note - you have a couple of options...

1,  increase the cron job to run at a closer interval
2, edit the dashboard to have this in each search `span=10m` so final search would be 

`first part of search | timechart span=10m max(something)`

i'll edit the dashboard to have this for next release

Cheers!
