### ISSUE TITLE
freenas_splunk-master/system_info 

### ISSUE THREAD

**Issue by fk319** [J-C-B/freenas_splunk#33]
Top row, middle panel.
The search does not have an index
        index = envfactors

**Comment by J-C-B** [comment]
Thanks for taking the time to comment :)

i have tuned the search to `source="rest://Weather" | spath main.temp_max | timechart max("main.temp_max") span=1h`

**Comment by J-C-B** [comment]
i also made the input go to the freenas index by default. i'll update the app on splunkbase later

**Comment by fk319** [comment]
in my config I have just main as my default index.
I do this to keep me in the habit of using index=  (something I preach about at work)
your tune, that you posted does not include an index.
and I think putting it in index=freenas is a good choice.

**Comment by J-C-B** [comment]
yes best practice for sure, was rushing - changed now to

`index="freenas" OR index="envfactors" source="rest://Weather"`

this allows for users who may have created the envfactors index previously - and the app i'll release shortly :)
