### ISSUE TITLE
need to add fixedrange=false to a timeline

### ISSUE THREAD

**Issue by fk319** [J-C-B/freenas_splunk#38]
I noticed on 
freenas_splunk-master/system_info
that I had a zero reported on my weather
to solve this:
source="rest://Auckland_Weather" index=envfactors | spath main.temp_max | timechart max("main.temp_max") span=1h
To:
source="rest://Auckland_Weather" index=envfactors 
| spath main.temp_max 
| timechart **fixedrange=false** max("main.temp_max") span=1h

**Comment by J-C-B** [comment]
Thanks - have added it - may also have been caused by the `span=` in the timechart but went with yours :)
